"use strict";
exports.__esModule = true;
// import express from "express";
var express = require("express");
var ordersController_1 = require("./../controllers/ordersController");
var authorizationMW_1 = require("./../middlewares/authorizationMW");
var ordersRouter = express.Router();
ordersRouter.get("/", authorizationMW_1["default"](), ordersController_1["default"].getOrders);
ordersRouter.get("/:id", authorizationMW_1["default"](), ordersController_1["default"].getOrders);
ordersRouter.post("/", authorizationMW_1["default"](), ordersController_1["default"].createOrder);
ordersRouter.put("/:id", authorizationMW_1["default"](), ordersController_1["default"].editOrders);
ordersRouter["delete"]("/:id", authorizationMW_1["default"](), ordersController_1["default"].deleteOrders);
exports["default"] = ordersRouter;
